---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2026-07-04T15:53:49.483998873-04:00"
  name: instavote
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/libialany/instavote.git
